apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10000"
spec:
  rules:
  - host: {{ .Values.host | quote }}
    http:
      paths: 
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 10000


